### ISSUE TITLE
Query not returning Tag info when using Daily or Hourly periodicity.

### ISSUE THREAD

**Issue by japoeder** [cduggn/ccExplorer#117]
Here is the query:

"ccexplorer get aws -g DIMENSION=SERVICE,TAG=Name -e {end} -s {start} -m DAILY -l -p csv"

Running from Jupyter - see attached for an screenshot of output.

![noTag](https://github.com/cduggn/ccExplorer/assets/8039100/83b18bf7-089b-4dc7-b952-7fddb155281a)

**Comment by cduggn** [comment]
@japoeder are you getting the same issue when sending to stdout?  Have you [configured ](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activating-tags.html) the tags as user-defined cost allocation tags?

**Comment by japoeder** [comment]
So, one point I should clarify is that technically the output is $Name for every record, not blank as it appears in the attached image.  When the tag does show up I remove that from the string.  '$Name' shows up in every record with stdout as well.  

Regarding the configuration - I think (and correct me if I'm wrong) the answer to your question is yes, because I'm able to see the expected output when setting the periodicity to monthly.

**Comment by cduggn** [comment]
Is this an AWS-generated cost allocation tag? There is a limitation with the number of [active tag keys per report](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/aws-tag-restrictions.html) which is 500 but in this case you have a single tag. 

When you filter by a specific $Name are you seeing the tags?

```bash
"ccexplorer get aws -g DIMENSION=SERVICE,TAG=Name -e {end} -s {start} -m DAILY -f Name="<some app name>" -l -p csv "
```

**Comment by cduggn** [comment]
@japoeder I would recommend either deleting those links or removing the account information contained within. I'm unable to recreate the issue you described locally but given that you can get the information when the granularity is Monthly I would be wondering if there is some nuance associated with the metering on your account. Is it possible that metering applied to your account is non-standard?  Feel free to fork this repo and try find root cause.

**Comment by japoeder** [comment]
Thanks for the heads up!  Where would I find the metering info related to cost explorer?  I went down a rabbit hole trying to find it and didn't have any luck...

**Comment by japoeder** [comment]
Hey - turns out I was able to get it working when I use the repo, but not the version installed with brew.  Thanks for your help on the matter.

**Comment by cduggn** [comment]
Good to hear. Out of interest what version were you using , you can check with `brew list --versions -v` . thanks
