### ISSUE TITLE
Specifying profile

### ISSUE THREAD

**Issue by cybertoast** [cduggn/ccExplorer#43]
Is there a way to specific the profile to use? I have multiple AWS accounts and would like to run ccexplorer against a specific named profile in ~/.aws/credentials.

**Comment by cduggn** [comment]
I think it would be reasonable to include this as an environment variable in the .ccexplorer env file. If the environment variable is not provided then it will fall back to default. I'll add that change over the weekend

**Comment by cduggn** [comment]
This is possible now by setting environment variable AWS_PROFILE 
`export AWS_PROFILE=profile-name`
